import type { Metadata } from "next";
import "./globals.css";
import AnalyticsDataInitializer from "@/components/Initializer/AnalyticsDataInitializer";
import { DashboardHeader } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AnalyticsDataInitializer />
        <DashboardHeader />
        {children}
      </body>
    </html>
  );
}
